services:
  - type: web
    name: student-exam-score-api
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn summative.API.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
